### ISSUE TITLE
Elias-Fano encoding fails to handle BitVectors with values greater than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by ashinn** [vigna/Sux4J#4]
The following test fails using sux4j 4.0.0 or 4.2.0:

```java
    @Test
    public void testEliasFanoEncoding() {
        final long n = (long)Integer.MAX_VALUE + 1L;  // ok without + 1L

        // this works
        // final LongList longs = new LongArrayList(new long[]{n, n+1});                                                         

        // this fails
        final BitVector longs = LongArrayBitVector.ofLength(n + 1L);
        longs.set(n);
        assertTrue(longs.getBoolean(n));  // ok

        // final Select select = new HintedBsearchSelect(new Rank9(longs));  // this works
        final Select select = new SparseSelect(longs);
        assertEquals(n, select.select(0));
  }
```

The error is:

```
testEliasFanoEncoding(com.indeed.mph.TestEliasFanoEncoding)  Time elapsed: 0.125 sec  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index (8589934591) is greater than or equal to length (3)
        at it.unimi.dsi.bits.AbstractBitVector.ensureRestrictedIndex(AbstractBitVector.java:58)
        at it.unimi.dsi.bits.LongArrayBitVector.set(LongArrayBitVector.java:377)
        at it.unimi.dsi.sux4j.util.EliasFanoMonotoneLongBigList.<init>(EliasFanoMonotoneLongBigList.java:254)
        at it.unimi.dsi.sux4j.util.EliasFanoMonotoneLongBigList.<init>(EliasFanoMonotoneLongBigList.java:224)
        at it.unimi.dsi.sux4j.bits.SparseSelect.<init>(SparseSelect.java:79)
        at it.unimi.dsi.sux4j.bits.SparseSelect.<init>(SparseSelect.java:65)
        at com.indeed.mph.TestEliasFanoEncoding.testEliasFanoEncoding(TestEliasFanoEncoding.java:31)
```

It works without error using the LongArrayList, and the HintedBsearchSelect works either way.

**Comment by vigna** [comment]
That's actually a bug in the LongSetView of a LongArrayBitVector—it will be fixed soon in the DSI utilitiesl
