### ISSUE TITLE
ZFastTrie - null pointer on add operation

### ISSUE THREAD

**Issue by cornelcreanga** [vigna/Sux4J#5]
Error message:

Exception in thread "main" java.lang.NullPointerException
	at it.unimi.dsi.sux4j.util.ZFastTrie.addBefore(ZFastTrie.java:778)
	at it.unimi.dsi.sux4j.util.ZFastTrie.add(ZFastTrie.java:1153)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at com.creanga.sux4jissues.ZFastTrieNullPointer.main(ZFastTrieNullPointer.java:17)

Sux4J version: 4.3.0

To reproduce the issue run the following class:

https://github.com/cornelcreanga/Sux4J-issues/blob/master/src/main/java/com/creanga/sux4jissues/ZFastTrieNullPointer.java

**Comment by vigna** [comment]
You cannot use a non-prefix-free transformation. It's written clearly in the documentation.
