### ISSUE TITLE
You provided no keys, but the bucketed hash store was not checked

### ISSUE THREAD

**Issue by binarybit10** [vigna/Sux4J#9]
I'm providing a bucketed hash store as shown below. The bucketed hash store size is 4480113. It works for a different set of keys.

Also, the program hangs after the exception, it's not being terminated correctly due to running threads?
```
 store = new BucketedHashStore<>(TransformationStrategies.rawByteArray(), outputPath.getParent().toFile());
 // adding 4480113 keys to store in a loop
 store.add(hash);


       
     mph = new GOVMinimalPerfectHashFunction.Builder<byte[]>()
                    .store(store)
                    .build();
```

```
Caused by: java.lang.IllegalStateException: You provided no keys, but the bucketed hash store was not checked
	at it.unimi.dsi.sux4j.mph.GOVMinimalPerfectHashFunction.<init>(GOVMinimalPerfectHashFunction.java:466)
	at it.unimi.dsi.sux4j.mph.GOVMinimalPerfectHashFunction$Builder.build(GOVMinimalPerfectHashFunction.java:271)
```

**Comment by binarybit10** [comment]
Additional info: 
All the keys are sha256 hashes
Ensured there are no duplicate keys

**Comment by binarybit10** [comment]
I replaced java HashSet that has the keys with  ObjectOpenCustomHashSet<byte[]> with hash strategy and it worked.
